@host = http://localhost:3000

@token = 

### get
GET {{host}}/files/{{token}}


### create file
POST {{host}}/create-file/{{token}}
Content-Type: application/json

{
  "folderId": ""
}


### create folder  
POST {{host}}/create-folder/{{token}}
Content-Type: application/json

{
  "folderName": "NewFoldFromNode insider",
  "folderId": ""
}